Vagrant.configure("2") do |config|
  config.vm.define "web" do |provider|
    provider.vm.box = "ubuntu/trusty64"
    provider.vm.hostname = "web"
    provider.vm.network "private_network", ip: "192.168.33.10"
    provider.vm.network "forwarded_port", guest: 80, host: 3000
  end

  config.vm.define "pg" do |provider|
    provider.vm.box = "ubuntu/trusty64"
    provider.vm.hostname = "pg"
    provider.vm.network "private_network", ip: "192.168.33.10"
  end
end
